version: "3"

services:
  gorl:
    build: .
    env_file: .env
    environment:
      - PORT=8000
      - DOMAIN=https://ly.cfrt.sh
    ports:
      - "80:8000"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine3.19
    env_file: .env_db
    volumes:
      - "./volumes/db:/var/lib/postgres/data"

volumes:
  db:
